name: Generate NuGet package

on:
  release:
    types: [published]
jobs:
  pack:
    name: Create NuGet package
    runs-on: windows-latest
    steps:

  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # get nuget
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1.0.5
    
    # package up the packages. 
    - name: create packages
      run: | 
        nuget pack DBMonad/DBMonad.nuspec -build -version ${{ github.event.release.tag_name }} -OutputDirectory .\output
    - name: Add Github Nuget repo
      run: |
        nuget setApiKey ${{ secrets.NugetAPI }}         
    
    - name: Publish to github nuget
      working-directory: .\output
      run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -NoSymbols
